/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package teoria1;

/**
 *
 * @author op7in
 */
public class inicio extends javax.swing.JFrame {

    /**
     * Creates new form inicio
     */
    public inicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        slidepane = new javax.swing.JPanel();
        boton1 = new javax.swing.JPanel();
        Legunaje1 = new javax.swing.JButton();
        boton2 = new javax.swing.JPanel();
        Lenguaje2 = new javax.swing.JButton();
        boton3 = new javax.swing.JPanel();
        Lenguaje4 = new javax.swing.JButton();
        boton4 = new javax.swing.JPanel();
        Teoria = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        slidepane.setBackground(new java.awt.Color(54, 33, 89));
        slidepane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        boton1.setBackground(new java.awt.Color(85, 55, 118));
        boton1.setLayout(new java.awt.BorderLayout());

        Legunaje1.setBackground(new java.awt.Color(85, 55, 118));
        Legunaje1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Legunaje1.setForeground(new java.awt.Color(255, 255, 255));
        Legunaje1.setText("Lenguaje1");
        Legunaje1.setToolTipText("");
        Legunaje1.setContentAreaFilled(false);
        Legunaje1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Legunaje1ActionPerformed(evt);
            }
        });
        boton1.add(Legunaje1, java.awt.BorderLayout.CENTER);

        slidepane.add(boton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 230, 70));

        boton2.setBackground(new java.awt.Color(102, 0, 102));
        boton2.setLayout(new java.awt.BorderLayout());

        Lenguaje2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Lenguaje2.setForeground(new java.awt.Color(255, 255, 255));
        Lenguaje2.setText("Lenguaje2");
        Lenguaje2.setContentAreaFilled(false);
        Lenguaje2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Lenguaje2ActionPerformed(evt);
            }
        });
        boton2.add(Lenguaje2, java.awt.BorderLayout.CENTER);

        slidepane.add(boton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 230, 60));

        boton3.setBackground(new java.awt.Color(85, 55, 118));
        boton3.setLayout(new java.awt.BorderLayout());

        Lenguaje4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Lenguaje4.setForeground(new java.awt.Color(255, 255, 255));
        Lenguaje4.setText("Lenguaje3");
        Lenguaje4.setContentAreaFilled(false);
        Lenguaje4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Lenguaje4ActionPerformed(evt);
            }
        });
        boton3.add(Lenguaje4, java.awt.BorderLayout.CENTER);

        slidepane.add(boton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 230, 60));

        boton4.setBackground(new java.awt.Color(102, 0, 102));
        boton4.setLayout(new java.awt.BorderLayout());

        Teoria.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Teoria.setForeground(new java.awt.Color(255, 255, 255));
        Teoria.setText("Teroria");
        Teoria.setContentAreaFilled(false);
        Teoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TeoriaActionPerformed(evt);
            }
        });
        boton4.add(Teoria, java.awt.BorderLayout.CENTER);

        slidepane.add(boton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 230, 60));

        bg.add(slidepane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 490));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        bg.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 550, 490));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Legunaje1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Legunaje1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Legunaje1ActionPerformed

    private void TeoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TeoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TeoriaActionPerformed

    private void Lenguaje2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Lenguaje2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Lenguaje2ActionPerformed

    private void Lenguaje4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Lenguaje4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Lenguaje4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Legunaje1;
    private javax.swing.JButton Lenguaje2;
    private javax.swing.JButton Lenguaje4;
    private javax.swing.JButton Teoria;
    private javax.swing.JPanel bg;
    public javax.swing.JPanel boton1;
    public javax.swing.JPanel boton2;
    public javax.swing.JPanel boton3;
    public javax.swing.JPanel boton4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel slidepane;
    // End of variables declaration//GEN-END:variables
}
