/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package teoria1;

import Automata.AutomataPila;
import javax.swing.JOptionPane;

/**
 *
 * @author op7in
 */
public class Interfaz extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz
     */
    private char[] sigma;
    private String[] palabras;
    private AutomataPila ap;

    public Interfaz() {

        initComponents();
        iniciarComponentes();
        ap = new AutomataPila();

    }

    private void iniciarComponentes() {
        alfabeto.setText("");
        validarPalabrasBtn.setEnabled(false);
        cargarPalabrasBtn.setEnabled(false);
        inputPalabras.setEnabled(false);
        outputValidacion.setEnabled(false);
    }

    private boolean comprobarEntradaAlfabeto(String alfabeto) {
        alfabeto = alfabeto.replace(" ", "");
        String[] caracteres = alfabeto.split(",");
        return caracteres.length==4;
    }


    private void obtenerAlfabeto() {
        String alfabet = this.alfabeto.getText();
        alfabet = alfabet.replace(",", "");
        sigma = alfabet.toCharArray();
    }

    private void obtenerPalabrasAValidar() {
    
        if (comprobarEntradaAlfabeto(alfabeto.getText())) {
            JOptionPane.showMessageDialog(null, "¡Ingrese una/s palabras para validar!", "¡No hay palabras para validar!", JOptionPane.ERROR_MESSAGE);
            inputPalabras.setEnabled(true);
        } else {
            palabras = inputPalabras.getText().split("\n");

            /*Quitamos los espacios de entrada y sallida */
            for (byte i = (byte) (palabras.length - 1); i >= 0; i--) {
                palabras[i].replace(" ", "");
            }

            JOptionPane.showMessageDialog(null, "¡Palabras cargadas con éxito!", "¡A validar!", JOptionPane.INFORMATION_MESSAGE);
            outputValidacion.setEnabled(true);
            validarPalabrasBtn.setEnabled(true);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jLabel4 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        alfabeto = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        inputPalabras = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        outputValidacion = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        w = new javax.swing.JLabel();
        y = new javax.swing.JLabel();
        x = new javax.swing.JLabel();
        z = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        alfabetoBtn = new javax.swing.JButton();
        cleanBtn = new javax.swing.JButton();
        validarPalabrasBtn = new javax.swing.JButton();
        cargarPalabrasBtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocationByPlatform(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/teoria1/WhatsApp Image 2022-06-03 at 8.55.13 PM.jpeg"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 470, 270, 200));

        jLabel11.setBackground(new java.awt.Color(0, 51, 153));
        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 51, 153));
        jLabel11.setText("Definición formal ");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 10, 220, 40));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Un autómata de pila posee la transiciones de la forma ");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 60, 450, 40));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("– T = Símbolo que se apila");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 210, -1, 20));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("– P = Estado Inicial");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 130, -1, 20));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("– Q = Estado al que llega");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 150, -1, 20));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("– X = Símbolo de la cadena de entrada");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 170, -1, 20));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("– S = Símbolo que se desapila");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 190, -1, 20));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Palabra: ");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 260, -1, -1));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Secuencia finita de símbolos de un alfabeto.");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 300, -1, -1));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Palabra vacía: palabra de longitud 0 (A = 0); es decir, no contiene ");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 350, -1, -1));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("ningún símbolo, en nuestro programa el vacío es representado por ");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 380, 520, -1));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("el carácter 'Z'");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 410, -1, -1));

        jPanel1.setBackground(new java.awt.Color(0, 63, 109));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/teoria1/logo_a.png"))); // NOI18N
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("Simulador Automata Pila");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, 220, 50));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Alfabeto:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 80, 30));

        alfabeto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        alfabeto.setForeground(new java.awt.Color(102, 102, 102));
        alfabeto.setText("  Ingrese el texto");
        alfabeto.setToolTipText("");
        alfabeto.setBorder(null);
        alfabeto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alfabetoActionPerformed(evt);
            }
        });
        jPanel2.add(alfabeto, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 410, 40));

        jPanel3.setBackground(new java.awt.Color(0, 153, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 410, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, 410, 2));

        inputPalabras.setColumns(20);
        inputPalabras.setRows(5);
        jScrollPane1.setViewportView(inputPalabras);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 330, 100));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Ingrese las palabras: ");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, -1, -1));

        outputValidacion.setColumns(20);
        outputValidacion.setRows(5);
        jScrollPane2.setViewportView(outputValidacion);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 470, 330, 100));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Resultado: ");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 440, -1, -1));

        w.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        w.setText("w");
        jPanel2.add(w, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 30, -1));

        y.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        y.setText(" y");
        jPanel2.add(y, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, 40, 30));
        y.getAccessibleContext().setAccessibleName("X");

        x.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        x.setText(" x");
        jPanel2.add(x, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 30, 30));

        z.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        z.setText("z");
        jPanel2.add(z, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 110, 20, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/teoria1/WhatsApp Image 2022-06-04 at 4.17.32 PM.jpeg"))); // NOI18N
        jLabel8.setMaximumSize(new java.awt.Dimension(100, 72));
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 390, 50));

        alfabetoBtn.setText("Validar alfabeto");
        alfabetoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alfabetoBtnActionPerformed(evt);
            }
        });
        jPanel2.add(alfabetoBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 240, 150, 30));

        cleanBtn.setText("Limpiar campos");
        cleanBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cleanBtnActionPerformed(evt);
            }
        });
        jPanel2.add(cleanBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 600, 150, 40));

        validarPalabrasBtn.setText("Validar palabras");
        validarPalabrasBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                validarPalabrasBtnActionPerformed(evt);
            }
        });
        jPanel2.add(validarPalabrasBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 490, 150, 40));

        cargarPalabrasBtn.setText("Cargar palabras");
        cargarPalabrasBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargarPalabrasBtnActionPerformed(evt);
            }
        });
        jPanel2.add(cargarPalabrasBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 350, 150, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 590, 650));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 690));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/teoria1/23183.jpg"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 0, 620, 690));

        jLabel24.setBackground(new java.awt.Color(0, 51, 153));
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("(P ,X ,S ,Q ,T), donde:");
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 100, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void alfabetoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alfabetoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alfabetoActionPerformed

    private void alfabetoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alfabetoBtnActionPerformed
        
        boolean valido = comprobarEntradaAlfabeto(alfabeto.getText());
        
        if (!valido) {
            JOptionPane.showMessageDialog(null, "¡El alfabeto debe estar compuesto de 4 caracteres!\n Ingrese el alfabeto con sus terminales separadas por comas", "¡Errore en el alfabeto", JOptionPane.ERROR_MESSAGE);
        }else{
            alfabeto.setEnabled(false);
            inputPalabras.setEnabled(true);
            cargarPalabrasBtn.setEnabled(true);
            obtenerAlfabeto();
            w.setText(String.valueOf(sigma[0]));
            x.setText(String.valueOf(sigma[1]));
            y.setText(String.valueOf(sigma[2]));
            z.setText(String.valueOf(sigma[3]));
        }

    }//GEN-LAST:event_alfabetoBtnActionPerformed

    private void cleanBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cleanBtnActionPerformed
        // TODO add your handling code here:
        alfabeto.setText("");
        alfabeto.setEnabled(true);
        
        inputPalabras.setText("");
        inputPalabras.setEnabled(false);
        
        outputValidacion.setText("");
        outputValidacion.setEnabled(false);
        
        validarPalabrasBtn.setEnabled(false);
        cargarPalabrasBtn.setEnabled(false);
    }//GEN-LAST:event_cleanBtnActionPerformed

    private void validarPalabrasBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_validarPalabrasBtnActionPerformed
        // TODO add your handling code here:
        boolean palabraValida = false;
        String mensaje = "";
        for (byte i = 0; i < palabras.length; i++) {
            
            palabraValida = ap.Verificacion(sigma, palabras[i]);
            
            mensaje = palabraValida ? "Palabra valida\n" : "Palbra no reconocida por el lenguaje\n";
            
            outputValidacion.setText(outputValidacion.getText() + mensaje);
        }
    }//GEN-LAST:event_validarPalabrasBtnActionPerformed

    private void cargarPalabrasBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargarPalabrasBtnActionPerformed
        // TODO add your handling code here:
        inputPalabras.setEnabled(false);
        obtenerPalabrasAValidar();
    }//GEN-LAST:event_cargarPalabrasBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alfabeto;
    private javax.swing.JButton alfabetoBtn;
    private javax.swing.JButton cargarPalabrasBtn;
    private javax.swing.JButton cleanBtn;
    private javax.swing.JTextArea inputPalabras;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea outputValidacion;
    private javax.swing.JButton validarPalabrasBtn;
    private javax.swing.JLabel w;
    private javax.swing.JLabel x;
    private javax.swing.JLabel y;
    private javax.swing.JLabel z;
    // End of variables declaration//GEN-END:variables
}
