/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.BorderLayout;
import java.awt.Desktop;
import java.net.URI;

/**
 *
 * @author op7in
 */
public class inicio extends javax.swing.JFrame {

    /**
     * Creates new form inicio
     */
    public inicio() {
        initComponents();
        this.setTitle("S_A_P_A");
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        slidepane = new javax.swing.JPanel();
        boton1 = new javax.swing.JPanel();
        Legunaje1 = new javax.swing.JButton();
        boton2 = new javax.swing.JPanel();
        Lenguaje2 = new javax.swing.JButton();
        boton3 = new javax.swing.JPanel();
        Lenguaje4 = new javax.swing.JButton();
        boton4 = new javax.swing.JPanel();
        Teoria = new javax.swing.JButton();
        content = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        slidepane.setBackground(new java.awt.Color(54, 33, 89));
        slidepane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        boton1.setBackground(new java.awt.Color(85, 55, 118));
        boton1.setLayout(new java.awt.BorderLayout());

        Legunaje1.setBackground(new java.awt.Color(85, 55, 118));
        Legunaje1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Legunaje1.setForeground(new java.awt.Color(255, 255, 255));
        Legunaje1.setText("L = a^n b^m");
        Legunaje1.setToolTipText("");
        Legunaje1.setContentAreaFilled(false);
        Legunaje1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Legunaje1ActionPerformed(evt);
            }
        });
        boton1.add(Legunaje1, java.awt.BorderLayout.CENTER);

        slidepane.add(boton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 230, 60));

        boton2.setBackground(new java.awt.Color(102, 0, 102));
        boton2.setLayout(new java.awt.BorderLayout());

        Lenguaje2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Lenguaje2.setForeground(new java.awt.Color(255, 255, 255));
        Lenguaje2.setText("L = a^n b^m c^p");
        Lenguaje2.setContentAreaFilled(false);
        Lenguaje2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Lenguaje2ActionPerformed(evt);
            }
        });
        boton2.add(Lenguaje2, java.awt.BorderLayout.CENTER);

        slidepane.add(boton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 230, 60));

        boton3.setBackground(new java.awt.Color(85, 55, 118));
        boton3.setLayout(new java.awt.BorderLayout());

        Lenguaje4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Lenguaje4.setForeground(new java.awt.Color(255, 255, 255));
        Lenguaje4.setText("L = a^n  b^m c^p d^o");
        Lenguaje4.setContentAreaFilled(false);
        Lenguaje4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Lenguaje4ActionPerformed(evt);
            }
        });
        boton3.add(Lenguaje4, java.awt.BorderLayout.CENTER);

        slidepane.add(boton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 230, 60));

        boton4.setBackground(new java.awt.Color(102, 0, 102));
        boton4.setLayout(new java.awt.BorderLayout());

        Teoria.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Teoria.setForeground(new java.awt.Color(255, 255, 255));
        Teoria.setText("Documentación");
        Teoria.setContentAreaFilled(false);
        Teoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TeoriaActionPerformed(evt);
            }
        });
        boton4.add(Teoria, java.awt.BorderLayout.CENTER);

        slidepane.add(boton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 230, 60));

        bg.add(slidepane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 520));

        content.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/manual.png"))); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/numeros.png"))); // NOI18N

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo_a.png"))); // NOI18N

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contentLayout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contentLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(38, 38, 38)
                        .addComponent(jLabel2))
                    .addComponent(jLabel4))
                .addGap(24, 24, 24))
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentLayout.createSequentialGroup()
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contentLayout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(contentLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        bg.add(content, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 600, 520));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Legunaje1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Legunaje1ActionPerformed
        Lenguaje1 in3 = new Lenguaje1();
        in3.setVisible(true);
        this.setVisible(false);  
                
    }//GEN-LAST:event_Legunaje1ActionPerformed

    private void TeoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TeoriaActionPerformed
        // TODO add your handling code here:
        try{
            Desktop.getDesktop().browse(new URI("https://docs.google.com/document/d/1XfZllxqGOo4Oj6MHzkfKEk-sZZiyaTSmE--ef0vndIQ/edit"));
        }catch(Exception e){
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_TeoriaActionPerformed

    private void Lenguaje2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Lenguaje2ActionPerformed
        Lenguaje2 in2 = new Lenguaje2();
        in2.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_Lenguaje2ActionPerformed

    private void Lenguaje4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Lenguaje4ActionPerformed
        Lenguaje3 in = new Lenguaje3();
        in.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_Lenguaje4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Legunaje1;
    private javax.swing.JButton Lenguaje2;
    private javax.swing.JButton Lenguaje4;
    private javax.swing.JButton Teoria;
    private javax.swing.JPanel bg;
    public javax.swing.JPanel boton1;
    public javax.swing.JPanel boton2;
    public javax.swing.JPanel boton3;
    public javax.swing.JPanel boton4;
    private javax.swing.JPanel content;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel slidepane;
    // End of variables declaration//GEN-END:variables
}
